"""Every number the README states is one the evaluation printed.

    uv run python scripts/check_readme_numbers.py                # README.md
    uv run python scripts/check_readme_numbers.py A.md B.md ...  # each file given

The sources are the files a number may be copied from:

* ``docs/eval/report-v1.md``, generated by ``make eval`` from the frozen run;
* ``docs/eval/report-v1-addendum.md``, the headline sentence and the labels;
* ``docs/eval/protocol.md``, the pre-registered counts, rules and exclusions,
  pinned by its SHA-256 in the run's manifest.

A number is any numeric token of the prose and the tables. A percentage has to
appear in a source as a percentage, a fraction such as ``13/300`` as that
fraction, and anything else as a numeric token; thousands separators and a
leading plus are ignored, so ``6,192`` matches ``6192`` and ``+0.6`` matches
``0.6``. A ``mermaid`` block is a diagram the page renders, so it is checked
like prose. Skipped, because they are not results: every other fenced code
block (commands, and the JSON responses ``tests/test_readme_contract.py`` holds
against the service), inline code (settings, model names, paths), HTML tags,
link targets, issue and pull request references (``#4``), ADR numbers
(``ADR-0014``) and the form name ``10-K``.

Exit status 1, with each missing number and its line, when one is not found.
"""

import re
import sys
from collections.abc import Iterable, Iterator
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
README = ROOT / "README.md"
SOURCES = (
    ROOT / "docs" / "eval" / "report-v1.md",
    ROOT / "docs" / "eval" / "report-v1-addendum.md",
    ROOT / "docs" / "eval" / "protocol.md",
)

FENCE = re.compile(r"^\s*(```|~~~)\s*(\w*)")
CHECKED_FENCES = frozenset({"mermaid"})
NOT_RESULTS = (
    re.compile(r"`[^`]*`"),  # inline code
    re.compile(r"</?[A-Za-z][^>]*>"),  # HTML tags and their attributes, such as an image width
    re.compile(r"\]\([^)]*\)"),  # link targets; the link text stays
    re.compile(r"https?://\S+"),
    re.compile(r"\w*#\d+"),  # ollama#15609, pull request #4
    re.compile(r"\bADR-\d{4}\b"),
    re.compile(r"\b10-Ks?\b"),
)
NUMBER = re.compile(
    r"(?<![\w.])"
    r"(?:"
    r"\d{4}-\d{2}-\d{2}"  # a date, as one token
    r"|\d[\d,]*/\d[\d,]*"  # a fraction, k/n
    r"|[+\-−]?(?:\d{1,3}(?:,\d{3})+|\d+)(?:\.\d+)*%?"
    r")"
    r"(?![\w/])"
)


def normalise(token: str) -> str:
    return token.replace("−", "-").replace(",", "").removeprefix("+")


def numbers(text: str) -> Iterator[str]:
    for match in NUMBER.finditer(text):
        yield normalise(match.group())


def prose_lines(text: str) -> Iterator[tuple[int, str]]:
    """The lines a reader sees as text: prose, tables and ``mermaid`` diagrams.

    Code spans, links and references are removed; fenced code other than a
    diagram is skipped whole.
    """
    fenced = False
    skipped = False
    for number, line in enumerate(text.splitlines(), start=1):
        fence = FENCE.match(line)
        if fence:
            fenced = not fenced
            skipped = fenced and fence.group(2).lower() not in CHECKED_FENCES
            continue
        if skipped:
            continue
        for pattern in NOT_RESULTS:
            line = pattern.sub(" ", line)
        yield number, line


def missing(readme: str, sources: Iterable[str]) -> list[tuple[int, str]]:
    """(line, number) for every number of ``readme`` that no source prints."""
    known = {token for source in sources for token in numbers(source)}
    return [
        (line, token)
        for line, text in prose_lines(readme)
        for token in numbers(text)
        if token not in known
    ]


def main(argv: list[str]) -> int:
    paths = [Path(arg) for arg in argv[1:]] or [README]
    sources = [source.read_text("utf-8") for source in SOURCES]
    failed = False
    for path in paths:
        absent = missing(path.read_text("utf-8"), sources)
        for line, token in absent:
            print(f"{path}:{line}: {token} appears in none of the evaluation reports")
        if absent:
            failed = True
        else:
            print(f"{path}: every number appears in the evaluation reports")
    if failed:
        names = ", ".join(str(source.relative_to(ROOT)) for source in SOURCES)
        print(f"a number in these pages is copied from one of: {names}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
